---
kind: Namespace
apiVersion: v1
metadata:
  name: odoo
  labels:
    name: odoo
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-db
  namespace: odoo
spec:
  labels:
    app: odoo-shop
spec:
  selector:
    app: odoo-shop
    tier: backend
  type: LoadBalencer
  ports:
    - port: 5432
    - targetPort: 5432
  externalIPs:
    - 192.168.1.169
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-db
  namespace: odoo
  labels:
    app: odoo-shop
spec:
  selector:
    matchLabels:
      app: odoo-shop
     #version: v1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: odoo-shop
        tier: backend
    spec:
      containers:
      - image: postgres:9.4
        name: odoo-db
        env:
        - name: POSTGRES_USER
          value: odoo
        - name: POSTGRES_PASSWORD
          value: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: odoo-db
        volumeMounts:
        - name: odoo-db-pvc
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: odoo-db-pvc
        persistentVolumeClaim:
          claimName: odoo-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-shop
  namespace: odoo
spec:
  labels:
    app: odoo-shop
spec:
  selector:
    app: odoo-shop
    tier: frontend
  type: LoadBalencer
  ports:
    - port: 8069
    - targetPort: 8069
  externalIPs:
    - 192.168.1.169
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-shop
  namespace: odoo
  labels:
    app: odoo-shop
spec:
  selector:
    matchLabels:
      app: odoo-shop
     #version: v1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: odoo-shop
        tier: frontend
    spec:
      containers:
        - image: assc2/imech:NET-$BUILD_NUMBER
          name: odoo-shop
          env:
          - name: USER
            value: odoo
          - name: PASSWORD
            value: password
          securityContext:
            privileged: true
            runAsUser: 0
          ports:
            - containerPort: 8069
              name: odoo
          volumeMounts:
          - name: odoo-pvc
            mountPath: /var/lib/odoo
      volumes:
      - name: odoo-pvc
        persistentVolumeClaim:
          claimName: odoo-pvc
