-----
kind: Namespace
apiVersion: v1
metadata:
  name: odoo
  labels:
    name: odoo
-----
apiVersion: v1
kind: Service
metadata:
  name: odoo-db
  namespace: odoo
spec:
  selector:
    app: odoo-shop
    tier: backend
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
  externalIPs:
    - 192.168.1.165
-----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-db
  namespace: odoo
  labels:
    app: odoo-shop
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: odoo-shop
  template:
    metadata:
      labels:
        app: odoo-shop
        tier: backend
    spec:
      containers:
      - image: postgres:9.4
        name: odoo-db
        env:
        - name: POSTGRES_USER
          value: odoo
        - name: POSTGRES_PASSWORD
          value: odoo
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: odoo-db
        volumeMounts:
         - name: odoo-db-pvc
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: odoo-db-pvc
        emptyDir: {}
-----
apiVersion: v1
kind: Service
metadata:
  name: odoo-shop
  namespace: odoo
spec:
  selector:
    app: odoo-shop
    tier: frontend
  type: LoadBalancer
  ports:
    - port: 8069
      targetPort: 8069
  externalIPs:
    - 192.168.1.165

-----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-shop
  namespace: odoo
  labels:
    app: odoo-shop
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: odoo-shop
  template:
    metadata:
      labels:
        app: odoo-shop
        tier: frontend
    spec:
      containers:
        - image: odoo:10.0
          name: odoo-shop
          env:
          - name: USER
            value: odoo
          - name: PASSWORD
            value: odoo
          - name: HOST
            value: odoo-db
          securityContext:
            privileged: true
            runAsUser: 0
          ports:
            - containerPort: 8069
              name: odoo
          volumeMounts:
          - name: odoo-pvc
            mountPath: /var/lib/odoo
          - name: odoo-addons-space
            mountPath: /mnt/extra-addons
      volumes:
      - name: odoo-pvc
        emptyDir: {}
      - name: odoo-addons-space
        persistentVolumeClaim:
         claimName: odoo-addons-claim
-----
kind: PersistentVolume
apiVersion: v1
metadata:
  name: odoo-addons
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/extra-addons"

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: odoo-addons-claim
  namespace: odoo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
